server:
  port: 6699

# 数据源配置
spring:
  datasource:
    username: root
    password: Hu123456
    url: jdbc:mysql://127.0.0.1:3306/mxg_member?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B0
    #mysql8版本以上驱动包指定新的驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    #   数据源其他配置, 在 DruidConfig配置类中手动绑定
    initialSize: 8
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL

mybatis-plus:
  type-aliases-package: com.mengxuegu.member.entity
  # xxxMapper.xml 路径
  mapper-locations: classpath:com/mengxuegu/member/mapper/xml/**.xml

# 日志级别，会打印sql语句
logging:
  level:
    com.mengxuegu.member.mapper: debug


#mengxuegu:
#  jwt:
#    config:
#      secretKey: mengxuegu # jwt令牌密钥
#      expires: 604800 # 单位秒，7天
